### PR TITLE
[WIP] lightweight musl-based stdenv to produce fully static binaries

### PR DESCRIPTION
**Pull request by proger**
This is an experiment to make nixpkgs less bloated and less boring.

As a result it gives a fully static Erlang R18.

### CODE REVIEW

**Comment by cstrahan** [comment]
Is `cross-musl-archive` somehow different from the `musl` in Nixpkgs?

**Comment by cstrahan** [comment]
Ah, of course. The `musl` package doesn't include a `gcc`/`ld`/etc suitable for cross compilation, just a wrapper script (`mussl-gcc`) and the `musl` libc.

**Comment by cstrahan** [comment]
I think @edolstra has expressed some disinterest in seeing general support for musl throughout nixpkgs (due to the inevitable explosion of patches to support building with musl), but I would think (or at least hope) that it would be acceptable to include a suitable stdenv and maybe support in just a couple popular compilers, allowing others to maintain their own musl compatible forks with much more ease than if we didn't include at least a little bit of support to help people get started.

So, I'd be very interested in trying to get something upstream :).

**Comment by proger** [comment]
Fair point, though it seems that it's around the same burden as having cross-compilation support (had to waste a night trying to build python for arm 😫) — I suppose having a standardised (versioned?) API for providing `stdenv`s would be a great middle ground to start with?

**Comment by cstrahan** [comment]
Looks like there was a recent commit that uses `musl` to build a package: https://github.com/NixOS/nixpkgs/commit/f1675d9137f97d125a0bfbc5977b1b4778b78629

I'm curious if using `wrapCCWith` is sufficient, or if the resulting wrapper still has too many `glibc`isms.

**Pull request closed without merging**
