### PR TITLE
Don't mount /tmp

### PR DESCRIPTION
**Pull request by 4z3**

### CODE REVIEW

**Comment by fmap** [comment]
lgtm

**Comment by proger** [comment]
We should remove support for ephemeral roots if we remove this.

**Comment by 4z3** [comment]
Can you elaborate/point to the support for ephemeral roots?

**Comment by proger** [comment]
https://github.com/zalora/microgram/blob/master/nixos/ec2/ami-s3.nix
https://github.com/zalora/microgram/blob/master/nixos/ec2/amazon-image.nix#L25-L97
https://github.com/zalora/microgram/blob/master/nixos/ec2/amazon-image.nix#L151-L154
https://github.com/zalora/microgram/blob/master/tests/nginx.nix#L43-L44

**Pull request merged**
