### PR TITLE
mariadb-galera: download source tarball from github

### PR DESCRIPTION
**Pull request by phunehehe**
downloads.mariadb.org gives funny 404s at times

### CODE REVIEW

**Comment by fmap** [comment]
Would be good if `fetchurl` `mirror://` were extensible, but meh.
The hash changed; how are the contents different? Builds okay?

**Comment by phunehehe** [comment]
built okay :)

**Comment by fmap** [comment]
:+1:

**Comment by phunehehe** [comment]
wee

**Pull request merged**
