### PR TITLE
VBox: allow-unsafe-native-code-during-evaluation + MariaDB bump

### PR DESCRIPTION
**Pull request by ip1981**

### CODE REVIEW

**Comment by ip1981** [comment]
- MariaDB 10.0.20

Older version tend to disappear from mirrors.

**Comment by proger** [comment]
Did you mean to put these changes into the same PR?

**Comment by ip1981** [comment]
It is two different commits. Do not read branch name :-)

**Comment by ip1981** [comment]
PR title, I mean

**Pull request merged**
