### PR TITLE
exportSessionVariables: only export variables if the file exists

### PR DESCRIPTION
**Pull request by phunehehe**
ref https://github.com/zalora/microgram/commit/799018ed0d901a01731e837202cbe34d66a22237#commitcomment-13658945

### CODE REVIEW

**Comment by proger** [comment]
That starts to feel really wrong

**Comment by ip1981** [comment]
Yeah, what if it's a symlink, a directory, or 'yes' :-)

**Comment by ip1981** [comment]
Or a file that the service should create.

**Comment by phunehehe** [comment]
but we know from this list right here that all of them are files

**Comment by proger** [comment]
The correct way to solve this is to reference the files as derivations (so the path is also a store path). If we have to resort to `test -f`, this means the hack no longer works.

**Comment by phunehehe** [comment]
> The correct way to solve this is to reference the files as derivations (so the path is also a store path)

That's cool, somehow I didn't think of it.

**Comment by phunehehe** [comment]
replaced by https://github.com/zalora/microgram/pull/45

**Pull request closed without merging**
